version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "updates"
    open-pull-requests-limit: 50
      
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "monthly"
    target-branch: "updates"
